<?php

namespace Nlc\InformationBundle\Repository;

/**
 * AdminuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminuserRepository extends \Doctrine\ORM\EntityRepository
{
}
